services:
  mariadb:
    image: mariadb:lts-ubi9
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: watch_party_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"  
    

  app:
    build: .
    deploy:
      replicas: 3
#    container_name: watch-party-app
#    ports:
#      - "8081:8081"
    depends_on:
      mariadb:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_STOMP_BROKER_RELAY_HOST: ${STOMP_HOST}
      JWT_SECRET: ${JWT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: uat
  gateway:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_started

volumes:
  mariadb_data:
    external: true
