spring:
  
  datasource:
#    url: jdbc:mysql://localhost:3306/streaming_app_using_springweb_db
    url: jdbc:mysql://localhost:3306/watch_party_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    

  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
#logging:
#  file:
#    path: ./logs